# Generated by Django 2.2.5 on 2019-11-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djuc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=2000)),
                ('email_address', models.CharField(max_length=2000)),
                ('content', models.TextField()),
            ],
        ),
    ]
